### ISSUE TITLE
课程资料：2016-03-01 CSS表格&列表样式练习

### ISSUE THREAD

**Issue by neekey** [neekey/F2ECourse#10]
``` html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CSS 属性表格练习</title>
    <link rel="stylesheet" href="css-table-style.css">
</head>
<body>

    <!-- 表格样式 练习 -->
    <table class="table-style">
        <thead>
            <tr>
                <th>商品名</th>
                <th>价格</th>
                <th>数量</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>饼干</td>
                <td>5元</td>
                <td>10包</td>
            </tr>
            <tr>
                <td>棒棒糖</td>
                <td>0.5元</td>
                <td>100根</td>
            </tr>
            <tr>
                <td>棒棒糖</td>
                <td>0.5元</td>
                <td>100根</td>
            </tr>
            <tr>
                <td>棒棒糖</td>
                <td>0.5元</td>
                <td>100根</td>
            </tr>
        </tbody>
    </table>

    <!-- 列表样式练习 -->
    <ul class="list-style">
        <li>麦芽糖</li>
        <li>棒棒糖</li>
        <li>葡萄糖</li>
    </ul>
</body>
</html>
```

css-table-style.css

``` css
/* 设置表格的样式 */
.table-style {
    border: 2px solid #ddd;

    /* 设置单元格之间的边框是否合并 collapse | separate */
    border-collapse: collapse;

    /* 单元格之间的距离 */
    border-spacing: 5px;
}

/* 设置单元格的样式 */
.table-style th,
.table-style td {
    border: 1px dashed #ddd;
    padding: 5px;
    text-align: center;
    border-left: 0;
    border-right: 0;
}

/* 单独设置表头的样式 */
.table-style th {
    font-size: 18px;
    font-weight: bold;
}

/* 单独设置内容单元格的样式 */
.table-style td {
    font-size: 16px;
    color: #999;
    background: #eee;
    height: 50px;
    width: 100px;

    /* 垂直居中 top | middle | bottom */
    vertical-align: middle;
}

.list-style {

    /* 设置列表图标类型(系统内置样式) disc | circle | square | none */
    list-style-type: disc;

    /* 为列表的项目图标设置自定义图片 */
    list-style-image: url(images/redis-icon.png);

    /* 设置列表标记图的位置
        outside: 图标展示在ul元素的元素内容左侧,
        如果是 inside, 图标 会被展示在列表项元素内容的前面
    */
    list-style-position: outside;
}
```
