### ISSUE TITLE
作业：2016-03-01

### ISSUE THREAD

**Issue by neekey** [neekey/F2ECourse#11]
## 背景图练习：

使用下面的图片素材作为背景图，在页面中展示一个如下的效果：

![image](https://cloud.githubusercontent.com/assets/499870/13421611/5ebe4eee-dfca-11e5-9846-832fb17d662f.png)
- [图片素材](http://g.alicdn.com/tb/jury/0.24.0/pages/index/page/images/s-sad3055c86e.png)
## 实现如下的效果：

![image](https://cloud.githubusercontent.com/assets/499870/13421663/b005e528-dfca-11e5-93e3-a235949c899e.png)
- 相关数据：
  - 字体大小： 12px
  - 按钮颜色： #F40
  - 字体颜色： 白色
  - 圆角： 2px
  - 按钮高度： 25px
  - 按钮高度： 75px
  - 按钮间距7px
- 要求两个按钮在一行显示
## 表格样式练习：

![image](https://cloud.githubusercontent.com/assets/499870/13421885/20989ea6-dfcc-11e5-839d-41f25128c71f.png)
- 样式近似即可

**Comment by niyun007** [comment]
1、
htm部分

``` html
          <div class="tupian" ></div>
```

css部分

``` CSS
.tupian{
    background-image:url(http://g.alicdn.com/tb/jury/0.24.0/pages/index/page/images/s-sad3055c86e.png);
    width:126px;
    height:18px;
    background-position:238px -1937px;
    }
```

2、
HTML部分

``` html
             <span class="zuoye2">免费注册</span>
             <span class="zuoye3">免费开店</span>
```

css部分

``` css
.zuoye2{
    background-color:#f40;
    display:inline-block;
    width:75px;
    height:25px;
    font-size:12px;
    color:#fff;
    line-height:27px;
    text-align:center;
    margin-right:7px;
       border-radius: 2px
}
.zuoye3{
    background-color:#f40;
    display:inline-block;
    width:75px;
    height:25px;
    font-size:12px;
    color:#fff;
    line-height:27px;
    text-align:center;
    margin-left:0;
        border-radius: 2px
}
```

3、
HTML部分

``` html
<table class="table-zuoye">
            <thead>
                <tr>
                    <th>商品名</th>
                    <th>价格</th>
                    <th>数量</th>
                <tr>    
            </thead>
            <tbody>
                <tr>
                    <td style="color:#999">饼干</td>
                    <td style="color:red">5元</td>
                    <td style="color:blue">10包</td>
                </tr>
                <tr>
                    <td style="color:#999">棒棒糖</td>
                    <td style="color:red">0.5元</td>
                    <td style="color:blue">100根</td>
                </tr>
                <tr>
                    <td style="color:#999">棒棒糖</td>
                    <td style="color:red">0.5元</td>
                    <td style="color:blue">100根</td>
                </tr>
                <tr>
                    <td style="color:#999">棒棒糖</td>
                    <td style="color:red">0.5元</td>
                    <td style="color:blue">100根</td>
            </tbody>
        </table>
```

css部分

``` css
.table-zuoye{
    border:2px solid #ccc;
    border-collapse:collapse;
    border-spacing:0;


}
.table-zuoye th,
.table-zuoye td{
    border:1px #ccc dashed;
    padding:15px;
    text-align:left;
    height:20px;
    width:75px;
    border-left:0;
    border-right:0;
}
.table-zuoye th{
    background:#ccc;
}

```

**Comment by neekey** [comment]
2、两个按钮样式基本一致，应该统一使用一个类来实现效果，不需要写两份一样的代码冗余。

3、也是没有进行代码复用的问题，以及不应该将CSS代码和HTML代码融合在一起的问题，更好的思路应该是为每种类型的样式添加类，然后在HTML中添加对应的类来制定样式效果：

``` html
<!-- 表格样式 练习 -->
    <table class="table-style">
        <thead>
            <tr>
                <th>商品名</th>
                <th>价格</th>
                <th>数量</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>饼干</td>
                <td class="price">5元</td>
                <td class="amount">10包</td>
            </tr>
            <tr>
                <td>棒棒糖</td>
                <td class="price">0.5元</td>
                <td class="amount">100根</td>
            </tr>
            <tr>
                <td>棒棒糖</td>
                <td class="price">0.5元</td>
                <td class="amount">100根</td>
            </tr>
            <tr>
                <td>棒棒糖</td>
                <td class="price">0.5元</td>
                <td class="amount">100根</td>
            </tr>
        </tbody>
    </table>
```

css

``` css
/* 设置表格的样式 */
.table-style {
    border: 2px solid #ddd;

    /* 设置单元格之间的边框是否合并 collapse | separate */
    border-collapse: collapse;

    /* 单元格之间的距离 */
    border-spacing: 5px;

    text-align: left;
}

/* 设置单元格的样式 */
.table-style th,
.table-style td {
    border: 1px dashed #ddd;
    padding: 5px;
    border-left: 0;
    border-right: 0;
}

/* 单独设置表头的样式 */
.table-style th {
    font-size: 18px;
    font-weight: bold;
    background: #eee;
}

/* 单独设置内容单元格的样式 */
.table-style td {
    font-size: 16px;
    color: #666;
    height: 50px;
    width: 100px;

    /* 垂直居中 top | middle | bottom */
    vertical-align: middle;
}

.table-style .price {
    color: red;
    text-decoration: underline;
}

.table-style .amount {
    color: blue;
}

```
