### ISSUE TITLE
作业：2016-03-02

### ISSUE THREAD

**Issue by neekey** [neekey/F2ECourse#14]
## 实现要求的PSD源文件效果：

![image](https://cloud.githubusercontent.com/assets/499870/13454558/f6da3468-e092-11e5-9141-83b46e97f38a.png)
- PSD 地址： `前端培训课程 > 课程资源 > 2016-03-02：CSS-切图练习-导航和搜索分类.psd`
- 基础HTML结构参考（已经包含菜单部分的实现）：

``` html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSS 实战之搜索结果</title>
    <link rel="stylesheet" href="taobao-search-menu.css">
</head>
<body>

    <!-- 菜单项 -->
    <ul class="menu">
        <li>所有宝贝</li>
        <li><a href="#">天猫</a></li>
        <li><a href="#">二手</a></li>
        <li class="selected"><a href="#">我的搜索</a></li>
        <li><a href="#">惠发现</a></li>
    </ul>

    <!-- 搜索结果总览 -->
    <div class="summary"></div>

    <!-- 搜索筛选项 -->
    <div class="filter"></div>
</body>
</html>
```

taobao-search-menu.css

``` css
/* ============== 菜单项 =============== */
.menu {
    list-style-type: none;
    font-size: 0;
    border-bottom: 2px solid #ff4300;
    padding: 0;
    width: 940px;
}

.menu li {
    display: inline-block;
    height: 38px;
    color: #333;
    line-height: 38px;
    font-size: 16px;
    padding: 0 20px;
}

.menu li a {
    color: #333;
    text-decoration: none;
}


.menu li.selected {
    background: #ff4300;
    color: white;
}

.menu li.selected a {
    color: white;
}


/* ============== 搜索总览 ============= */
.summary {

}

/* ============== 搜索过滤项 ============= */
.filter {

}

```
