### ISSUE TITLE
作业：2016-02-25

### ISSUE THREAD

**Issue by neekey** [neekey/F2ECourse#2]
## 1、什么是CSS，他的作用是什么？
- 请用自己的话来尽量详细的表达
## 2、怎么理解内容和样式分离？
- 尽量详细的用文字描述你的理解
- 可以举例说明
## 3、请列出三种将样式添加到HTML元素上的方式：
- 写出三种方式的名称
- 写出没放方式的代码示例
## 4、如果去掉列表元素的默认项目标记：
- 写出示例代码
## 5、添加一个列表并添加下面的图片素材作为项目标记：
- 给出实现代码
- [图片素材](https://cloud.githubusercontent.com/assets/499870/13312243/fc051704-dbcf-11e5-8506-f069cdae6e94.jpg)
- 无需下载图片到本地，复制改图片地址作为图片地址即可
## 6、实现一个类似下图样式的表格：

![image](https://cloud.githubusercontent.com/assets/499870/13312222/caf9b52a-dbcf-11e5-9fb6-21b4f25876c0.png)
- 贴出实现代码
- 相关参考数据：
  - 边框颜色： #ccc
  - 单元格间距： 5px
  - 边框宽度： 1px
## 7、添加一个`div`元素，并实现如下效果：

![image](https://cloud.githubusercontent.com/assets/499870/13312520/55532164-dbd2-11e5-96bf-bdf5c85ba99d.png)
- 贴出实现代码
- 相关参考数据：
  - 宽高： 800x600
  - 背景色：#87a8c3
- 图片水平垂直居中
- [图片素材](https://cloud.githubusercontent.com/assets/499870/13313960/fa2ee060-dbdc-11e5-86f6-bc8189a15d86.png)
## 8、CSS的色值有哪几种表达方式呢，并举例回答：
- 列出各种表达方式，并举例，如`#aaa123`
## 9、如何理解CSS中的数值单位 `em`和`rem`，描述并举例回答：
- 先用文字简单描述两个单位
- 再举例子说明实际的使用

**Comment by niyun007** [comment]
1、CSS(Cascading Style Sheet),即层叠样式表，用于对HTML的外观进行描述以及定义。
2、内容与样式分离就是指把HTML里的文案内容与CSS的外观描述定义分离与区分开来，以便更好的查看代码。
HTML里的标签以及元素过多或有多个甚至成百上千个HTML页，无法做到一个个页面去修改重新定义标签元素，这时可以利用CSS来快速的对一页或多页的HTML里的标签元素进行新的定义和描述。
3、三种将样式添加到HTML元素上的方式分别是：

1)、内联样式:`Style`属性

``` html
    <p style="color: sienna; margin-left: 20px">
    </p>    
```

2)、页面内部样式：`<Style>` 标签

``` html
      <head>
            <style type="text/css">
            hr {color:red;}
            p {margin-left: 10px;}
            </style>
      </head>
```

3)、外部样式文件：利用`<link>`标签来连接CSS文件来读取样式

``` html
<head>
<link rel="stylesheet" type="text/css" href="mystyle.css" />
</head>
```

4、

``` css
ul {
    list-style-type:none;｝
```

5、

``` html
<ul>
    <li>1</li>
</ul>
```

``` css
ul{
    list-style-image:url(https://cloud.githubusercontent.com/assets/499870/13312243/fc051704-dbcf-11e5-8506-f069cdae6e94.jpg);    
}

```

6、

``` html
<table  id="N table">
     <thead>
               <tr>
                    <th>货品名</th>
                    <th>单价</th>
                    <th>库存量</th>
               </tr>
      </thead>
      <tbody>
              <tr>
                    <td>枸杞（小）</td>
                    <td>45</td>
                    <td>100</td>
               </tr>
               <tr>
                    <td>枸杞（中）</td>
                    <td>55</td>
                    <td>200</td>
               </tr>
               <tr>
                    <td>枸杞（大）</td>
                    <td>65</td>
                    <td>50</td>
               </tr>
         </tbody>
```

``` css
#ntable th,#ntable td{
             border:1px   solid   #ccc;
             border-collapse:separate;
             border-spacing:5px;
             text-align:center;             
}
```

7、

``` html
<div id="h2">
</di>
```

``` css

h2{
     background-color:#87a8c3;
     width:800px;
     height:600px;
     background-position:50% 50%;
     background-image:url (https://cloud.githubusercontent.com/assets/499870/13313960/fa2ee060-dbdc-11e5-86f6-bc8189a15d86.png);
}

```

8、CSS的色值有三种表达方式:1是直观的表达方式，如`red`、`blue`、`black`等。2是以十六进制来表达，如`#000`、`#fffff`f等，数值越小，颜色越深，越大则越浅。3是以RGB和RGBA的形式来表达，如`rgb(255,224,212)`、`rgba(255,250,241,0,3)`
9、CSS的`em`数值是相对于父级元素的`font-size`的大小,如下列代码中`2em`等与`20px`,`1em`等于`20px`

``` html
div  font-size: 10px
    div fonts-zie: 2em
        div font-size: 1em
```

而rem值是相对与根元素的font-size的数值大小，如下面代码中,2rem等于20px，1rem等于10px

``` html
html font-size: 10px
    div fonts-zie: 2rem
        div font-size: 1rem
```
