### ISSUE TITLE
作业：2016-02-26

### ISSUE THREAD

**Issue by neekey** [neekey/F2ECourse#3]
## 2、如何使用通配符对页面的中的元素的常用样式进行重置
- 包含示例代码
## 5、外边距重叠的基本规则？
- 用文字列出规则
## 6、外边距重叠有哪三种基本场景，举例说明？
- 包含场景描述
- 包含代码示例
## 7、块级元素和行内元素是否可以进行相互转化？
- 说明如何转化
- 包含转化代码

**Comment by niyun007** [comment]
1、CSS的中的框模型含有以下几种属性：内容区域（内容区域可以用width和height来设置宽高尺寸）、内边距（内边距可以用padding来进行定义）、边框（边框可以用border来定义）以及外边距（外边距可以用margin来定义）。

2、通配符可以用*｛｝的形式来对页面里的元素来进行属性修改重置

``` css
*{
   margin:o;
   padding:o;
border:0;
}
```

3、在框模型中，背景色的范围包括：内边距和宽高。

4、行内元素span与块级元素div的区别在于：div块级元素不会同其他元素在同一行出现，块级元素可以对上下左右内边距进行设置。行内元素span可以与其他元素位于同一行，可以对水平间的内间距进行设置，但不能对垂直间的内边距进行设置。

5、当两个垂直的外边距相遇时，会重叠为一个，重叠的外边距大小取较大的外边距数值。

6、外边距的重叠现象有三种：兄弟重叠、父子重叠、以及自我重叠三种。
 1、兄弟重叠：当一个元素出现在另一个元素的下面时，中间没有阻隔，上面的元素下外边距与下面元素的上外边距会进行重叠，重叠的数值取较大的那一个元素的外边距数值。下列的外边距合并后的数值等于60，取book2的外边距数值。

下列的外边距合并后的数值等于60，取book2的外边距数值。

``` html
   <div id="food1">
   </div>
   <div id="food2">
   </div>
```

``` css
#food1{
       width：2px；
       height：2p'x
       margin-bottom:50px;
      background-color:blue;
}
#food2{
       width:2px;
       height:2px;
       margin-top:60px;
       background-color:red;
}
```

 2、父子重叠：当一个元素包含在另一个元素里是，元素1的外边距与元素2的外边距之间没有阻隔时，两者的外边距会进行重叠，重叠的数值取决于数值较大的数值。下列的外边距合并后的数值等于60，取‘’book2‘’的外边距数值。

``` html
   <div id="book1">
          <div id="book2">
          </div>
   </div>
```

``` css
#book1{
       width：2px；
       height：2px；
       margin-bottom:50px;
       background-color:blue;

}
#book2{
       width:2px;
       height:2px;
       margin-top:60px;
       background-color:red;
}
```

3、自我重叠：当一个个元素在没有内边距没有边框没有内容空间的情况下，这个元素的上下外边距会进行重叠.

``` html
<div id="foot">
foot
</div>
```

``` css
#foot{
        margin-top:50px;
        margin-bottom:60px
}
```

7、块级元素与行内元素可以用display属性来进行相互转换。
用display：inline属性来把块级元素转换为行内元素

``` html
<div style="display:inline;">asd</div>
```

用display：block属性来把行内元素转换为块级元素

``` html
<span style="display:block;">asd</span>
```

还可以用display：inline-block属性把该元素变为行内块级元素。

``` html
<div style="display:inline-block">asd</div>
```

8、行内块级元素可以用display：inline-block来表示，它与行内元素和块级元素最大的区别在于，它即可像行内元素一样与其他元素同处于同一水平的行内，也可以像块级元素一样可以对上下设置来对宽高进行设置。

9、css中的普通文档流是html页面中的元素是安元素的优先级来进行布置布局，使用的元素不同，所显示的位置也会不同，常用的有div块级元素和span行内元素等。
