### ISSUE TITLE
作业：2016-02-29

### ISSUE THREAD

**Issue by neekey** [neekey/F2ECourse#7]
## 写一个最简单的HTML完整结构
- 包含 `doctype`, `html`, `head`, `body`
- 给出代码
## 回答关于类属性的几个问题：
- 类属性在html中的写法？
- 如何为一个元素添加多个类？
- CSS中类选择器的写法？
## 类选择器练习：
- 定义三个类选择器，分别定义关于 “字体大小”，“背景色”，“字体颜色” 三方面的属性。
- 在HTML中随意添加三个HTML元素，并添加简单的内容。
- 利用定义好的三个类选择器，两两组合为这三个HTML元素添加样式

**Comment by niyun007** [comment]
1、
最简单的HTML完整结构

``` html
<!doctype html>
<html>
<head>
</head>
<body>
</body>
</html>
```

2、
类属性在html中的写法

``` html
<h class="book-bg ">
```

为一个元素添加多个类

``` html
<h class="book-bg book-cb">
```

类选择器在css中的写法

``` css
.book-gb{
               bcakground-color:red;
               font-size:25px;
}
```

3、

``` html
<h1 class="nbook1 nbook2">123</h1>
<h2 class="nbook2 nbook3">456</h2>
<h3 class="nbook1 nbook3">789</h3>
```

``` css
.nbook1{
                background-color:red;
}
nbook2{
                color:blue;
}
nbook3{
                font-size:25px;
}
```
