### ISSUE TITLE
课程资料：2016-03-01 CSS文字颜色练习

### ISSUE THREAD

**Issue by neekey** [neekey/F2ECourse#9]
``` html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>CSS 属性练习:文字样式</title>
    <link rel="stylesheet" href="css-text-style.css">
</head>
<body>

    <!-- 按钮效果练习 -->
    <div class="text-button">我是一个按钮</div>

    <!-- 利用 radius 绘制一个圆 -->
    <div class="circle"></div>

    <!-- 文字样式效果练习 -->
    <div class="css-text" style="
    width: 400px;
    background: yellow;
    ">
        <!-- br 是一个用于换行的标签 -->
        <p>这是CSS的文字样式练习<br />这是CSS的文字样</p>
        <p>式练习这是CSS的文字样式练习</p>
    </div>
</body>
</html>
```

css-text-style.css

``` css
.css-text {

    /* 字体颜色 */
    color: red;

    /* 字体大小 */
    font-size: 24px;

    /* 字体粗细  100 - 900 常用 normal | bold  */
    font-weight: bold;

    /* 行高   理解为 一行文字到下一行文字的距离 */
    line-height: 40px;

    /* 文字的水平对齐方式  left | right | center  */
    text-align: center;

    /* 首行文字缩进 */
    text-indent: 40px;

    /* 文字的装饰效果 none | underline | line-through  */
    text-decoration: none;

    /* 空值 空白/回车 的显示方式 和 是否换行  normal | nowrap | pre  */
    white-space: normal;
}

/* 利用行高来设置内容的整体高度并实现 垂直文字居中 */
.text-button {
    font-size: 16px;
    line-height: 42px;
    background: #f40;
    width: 300px;
    text-align: center;
    color: white;

    /* 圆角效果  radius 半径 */
    border-radius: 10px;
}

/* CSS的hover 伪类 */
.text-button:hover {
    background: orange;
    font-size: 24px;
}

/* 利用 border-radius 绘制一个圆形 */
.circle {
    width: 50px;
    height: 50px;
    background: pink;
    border: #f800f8 solid 5px;
    border-radius: 50%;
}
```
